### ISSUE TITLE
Exporter state changes are lost if no event is written to logstream

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#2490]
Currently, if we start a broker with no exporter it will remove it from the state but, if no event is written, then when the broker closes no snapshot will be taken because the processed position didn't change. When we restart the broker, we will recover from the latest snapshot which will contain the outdated exporter state. The test `ExporterManagerTest#shouldRemoveExporterFromState` works around this limitation by publishing an event so the snapshot is taken.

**Comment by npepinpe** [comment]
Just to see if I understand correctly:

1. We have an exporter, it's at position X in the snapshot
1. We stop the broker, remove the exporter, restart the broker
1. The exporter is removed from the runtime
1. No snapshot is taken because no processing occurs __and__ the exporter was up to date (note that if the exporter was behind, when we try to take a snapshot the new lowest position will be higher so we should take a snapshot)
1. The broker is stopped
1. The broker is restarted, and the exporter is re-added, and now recovers from the last position it was at.

So if we didn't process anything, then we have two options: either the exporter we removed was behind, and we can now take a snapshot, or it was up to date, and no snapshot is taken.

If a snapshot is taken, great, problem solved. If no snapshot is taken, on restart, if we re-add the exporter with the same ID, then it will recover the old position, which will not have been compacted since no snapshot was taken. If we don't re-add any exporter with that ID, then it will get cleared again.

I'm not sure I see the bug here - I think it looks a little strange, sure, but I don't think there's any consequences? I'm probably missing something.

**Comment by MiguelPires** [comment]
I may be misremembering but I think that we wrote a test that required a snapshot which never happened if there was no event. As a workaround, we published an event so it would be triggered. This issue was opened to eventually remove it . Here's that test: https://github.com/zeebe-io/zeebe/blob/fb1a1db6d928f3c7a387835b04208205cc911c53/broker-core/src/test/java/io/zeebe/broker/exporter/ExporterManagerTest.java#L100-L102
I can't find the test and the behavior has since changed so I think this issue is no longer valid and can be closed
