### ISSUE TITLE
Split address and port in zbctl

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#3104]
**Describe the solution you'd like**
Split address and port in zbctl, so the port can be defaulted

**Additional context**
Related to this comment: https://github.com/zeebe-io/zeebe/issues/3087#issuecomment-532993920

**Comment by aivinog1** [comment]
@MiguelPires @npepinpe Hi! I want to take this task, but I'm thinking about backward compatibility. Should we keep the old address flag or we can just remove it? For example, I think about this flow:
1. Look at the host or the port flags, if one of them exists
1.1. If the host exists we use it otherwise check the ZEEBE_HOST environment variable otherwise use default value: 127.0.0.1
1.2. If the port exists we use it otherwise check the ZEEBE_PORT environment variable otherwise use default value: 26500
2. Look at the address flag, if it exists we use it
3. If the ZEEBE_HOST environment variable exists use it and check port like 1.2.
4. If the ZEEBE_PORT environment variable exists use it and check host like 1.1.
5. If the ZEEBE_ADDRESS environment variable exists use it.
6. Otherwise use defaults.
Also, we can deprecate the address flag and remove it in the future.
