### ISSUE TITLE
Define Zeebe's BPMN Testing Story

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#3419]
**Description**

We need a clear story how users test BPMN Processes with Zeebe.

**Comment by berndruecker** [comment]
Current approaches (not saying this is the way to go! Just listing): 

- https://github.com/zeebe-io/zeebe-test-container
- ZeebeTestRule, see https://docs.zeebe.io/java-client/testing.html

**Comment by berndruecker** [comment]
Requirements:

- Drive workflows within unit test via some API, requiring fast startup times & isolated test runs
- Query capabilities (to do required assertions)
- Support polyglot environments
- Ideally self contained tests and no third party requirement, so nothing I have to run myself locally

**Comment by berndruecker** [comment]
Ideas and questions we bounced briefly:

- Doesn't need to be the full broker with gateway, event-handling loop and stream processors, etc... So some lightweight component just doing the workflow execution might be sufficient
- Some Exporter could listen to all events a provide a query API - probably even an assertion API on top
- How much can we align the testing stories of polyglot environments?

**Comment by berndruecker** [comment]
Looking at e.g. https://github.com/zeebe-io/zeebe-http-worker/blob/master/src/test/java/io/zeebe/http/WorkflowTest.java the current JUnit Rule seems not to be the best idea, because:

- It is relatively slow in startup
- The life cycle does not completely work correct, especially when using Spring Zeebe I have exceptions on shutdown (which do not harm the test, but are ugly)
- I can't create a second test class with that rule, that did not work at all for me

**Comment by saig0** [comment]
Currently, I'm building a query API that could be later used to build assertions on top: https://github.com/zeebe-io/zeeqs. Together with test-containers, we would have an isolated environment for polyglot clients.

**Comment by npepinpe** [comment]
We're currently working on `camunda-cloud-testing` in a separate project - I believe we can close this as this will clearly supersede that. Let me know if you think otherwise. See https://github.com/camunda-cloud/camunda-cloud-testing/milestone/1
