### ISSUE TITLE
Subscribed workers management tool

### ISSUE THREAD

**Issue by jstrmen** [camunda-cloud/zeebe#3595]
**Is your feature request related to a problem? Please describe.**
When I want to use Zeebe as microservices orchestration tool (without additional messaging platform) I am not able to monitor registered/subscribed workers (and its details). So for example when debugging, I am not able to determine who is consuming what tasks. Or when I want to create new worker, there is no simple way to find list of already registered workers or existing job-types (service-tasks) in deployed workflows. 

**Describe the solution you'd like**
It would be greate to have gui to see who is subscribed for which job (with all details of subscribed worker). Compared for example to RabbitMQ management plugin, where I have detailed description of all connections and all bindings for each exchange and routing key. 
Also would be great to have a list of all deployed service tasks with links to workflows, where they are used. So when (in bigger project with lot of developers involved) I am developing new workflow with new workers, I can easily check whether service-tasks (job-types) with given names already exists or not. And if they exists, where are they used (in what workflow) and then who is consuming them.   

**Describe alternatives you've considered**
- 

**Additional context**
-

**Comment by saig0** [comment]
@jstrmen, thank you for raising this up! It is an interesting and valid feature request.

Currently, the job workers are just polling from the broker. The subscriptions itself are not managed by the broker. Since the requests may be blocked in the gateway if no jobs are available for the given job type, the broker does not have the information.  

Note that we have no plan to implement something like that in the near future.

**Comment by npepinpe** [comment]
I will close this for the time being, as it's not anywhere on our short to mid term roadmap, and as saig0 commented, it's not something that could be done at the moment.
