### ISSUE TITLE
add information about the calling workflow instance to the activated job properties

### ISSUE THREAD

**Issue by SHOZ2020** [camunda-cloud/zeebe#4499]
**Is your feature request related to a problem? Please describe.**
As a large organisation we are looking at federating out the building of processes on Zeebe. This gives us the challenge of authorising that a sub-process can be called by another process.

**Describe the solution you'd like**
Include the details of the calling workflow in the activated job properties. The details of the calling workflow can then be examined to ensure that the caller is authorised.

**Describe alternatives you've considered**
Passing in the calling workflows details via variables. The issue is that this is too easily spoofed.

**Additional context**
Please see discussion - https://forum.zeebe.io/t/accessing-variables/1189/11

**Comment by SHOZ2020** [comment]
Hi - is there any way to progress this?

**Comment by saig0** [comment]
Hi @SHOZ2020,

the issue will be discussed by the stakeholders. They decide if and when we want to build this feature.

Please be aware that we have limited resources and need to make sure that we're working on the most important topics for the project and the users :)

**Comment by npepinpe** [comment]
The activated job currently carries the following instance properties:

- key of the process instance
- BPMN process id of the process definition
- version of the process definition
- key of the process definition
- id of the flow element (e.g. the service task for this job)
- key of the flow element instance (e.g. the service task for this job)

Is this sufficient for you? If so, then I would close this. Let me know - otherwise I will close this anyway in two weeks.
