### ISSUE TITLE
Wrong values for current WFI and stream processor/exporter metrics/graphs

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#4657]
**Describe the bug**

I can see I have a negative amount of running workflow instances and jobs, and a negative amount of processed/exported events. The former should never happen, the latter is possible but in my case it is much, much lower than expected. My current hypothesis is this is related to reprocessing and miscalculating the current values, but I'm not sure.

**To Reproduce**

This occurred while performing a long running test, so while you could do this, it can be quite time consuming. You can try triggering failovers, see if it happens.

**Expected behavior**

I expect that the `Running Workflow Instances` is never negative - that makes no sense. As for the stream processor vs exporter, I expect it to be as accurate as possible.

**Environment:**
 - OS: k8s
 - Zeebe Version: 0.24.0-alpha2
 - Configuration: Elasticsearch exporter enabled

**Comment by jetdream** [comment]
These incorrect metrics make really difficult to analyse the real issues

**Comment by Zelldon** [comment]
Possible ways to fix it:

 * Either you recalculate the number of existing workflow instances to set the gauge correct on restart
 * You store the existing workflow instance in the state and use it to reset the gauge on restart
 * You use two counters one for starting workflows and one for completing them 
     * https://de.slideshare.net/brianbrazil/counting-with-prometheus-cloudnativeconkubecon-europe-2017#:~:text=Prometheus%20Counters%3A%20Resets%20Counters%20can,5%20%3D%2015%20of%20an%20increase. 
     * https://stackoverflow.com/a/60480775/2165134

**Comment by npepinpe** [comment]
I like the two counters approach, any downsides we could expect?

**Comment by Zelldon** [comment]
I think it is build for that. As far as I understood the gauge should more used for showing different states otherwise you use counters. Prometheus is then able to detect restarts etc.

**Comment by deepthidevaki** [comment]
How does it work with reprocessing? Would some get counted twice?

**Comment by Zelldon** [comment]
Counters are reseted to zero, but at calculating the rate it can detect it - I think I need to play around with that to give a better answer :) 

I think this example makes it more clear:


> Prometheus Counters: Resets Counters can be reset to 0, such as if a process restarts or a network switch gets rebooted. If we see the value decreasing, then that's a counter reset so presume it went to 0. So seeing 0 -> 10 -> 5 is 10 + 5 = 15 of an increase.
> https://de.slideshare.net/brianbrazil/counting-with-prometheus-cloudnativeconkubecon-europe-2017#:~:text=Prometheus%20Counters%3A%20Resets%20Counters%20can,5%20%3D%2015%20of%20an%20increase

**Comment by npepinpe** [comment]
Hm - we would reset it before reprocessing and count it normally after wards, no? If we just look at the increase it should be fine at that point, and we don't need to know how many were already there? Maybe @ztombol has some idea there, but we could just try it out and see, shouldn't be too hard to verify.

**Comment by Zelldon** [comment]
> How does it work with reprocessing? Would some get counted twice?

Sorry @deepthidevaki i misinterpreted your last comment. I think we can skip counting metrics on reprocessing if we make it part of side-effects. :)

**Comment by Zelldon** [comment]
Ok maybe it is easier to just restore the gauge with an value from the state. I tried it with the counters and had some problems to get it working.

I can show the rate of created and completed separately, but the substraction of the rate/irate is not really useful. It is quite low and of course it can be negative, since I can complete more instances some minutes later which I started earlier. It is hard to show that I already have some running instances.

**Examples:**


**Via irate:**

![sum-irate](https://user-images.githubusercontent.com/2758593/105289935-8b0e1c80-5bb8-11eb-8ddb-12b75150149f.png)

**Via increase:**
![sum-increase](https://user-images.githubusercontent.com/2758593/105289940-8b0e1c80-5bb8-11eb-99fc-ec523c6f6775.png)

How it should really look like:

![sum-only-counts](https://user-images.githubusercontent.com/2758593/105289930-8a758600-5bb8-11eb-887b-5a92c9cf39f7.png)


I can get this *kind-of* via a longer period of time with rate/irate, but this is I think also not the correct, because if I coming out of the window it breaks.

![sum-ratelong-period](https://user-images.githubusercontent.com/2758593/105289909-89445900-5bb8-11eb-8904-91fcede9416b.png)

**AND** Only the counts also didn't work because they then are not restart aware this only works with the rate function.

![sum-only-counts-restart](https://user-images.githubusercontent.com/2758593/105289920-89dcef80-5bb8-11eb-9c2d-d2b89ece7c27.png)

**Comment by korthout** [comment]
@npepinpe This topic was brought up during the incident review of [2021-07-16 COMPLETED Missing process instances](https://docs.google.com/document/d/1egZgP7oFgcLUzYxo6hbdIuIICvbkxGgd71a97lKz38U/edit#)

**Comment by npepinpe** [comment]
Counting the currently running may be a blocker on large states, since everything is in the same column family. Of course, you could carry this in the snapshot itself, so you wouldn't have to traverse it every time on fail over. But as you mentioned, accuracy isn't really the best fit for Prometheus, and what we want is more of an idea about the rate.

So let's say we reset it to 0 on every leader change. Is that so bad? Assuming this is a known limitation, of course. I guess one downside I see is if you had many long living processes - then you run into a similar problem, where it shows you have a small rate but really there's currently a ton of running processes.

Maybe keep some basic aggregates in the state itself isn't that bad? Number of process instances, number of jobs, number of deployed processes, etc. I don't expect this would have a huge impact on performance? Though it is one additional write per transaction in the worse case. I get that in itself it's not terrible, but every write most likely adds up over time. Although this isn't something public or anything, so we could always start with this and find a better solution.

You mention that this causes confusion - does it also cause us to make wrong assumptions and waste time?

**Comment by deepthidevaki** [comment]
:thought_balloon: Do we really need this metric? What value does it give us? If we want to know if there are any running instances, we can check Operate. Isn't that enough?

**Comment by Zelldon** [comment]
If operate works and is up to date yes :sweat_smile: 

> Counting the currently running may be a blocker on large states, since everything is in the same column family. Of course, you could carry this in the snapshot itself, so you wouldn't have to traverse it every time on fail over. But as you mentioned, accuracy isn't really the best fit for Prometheus, and what we want is more of an idea about the rate.

Not sure whether I get this. My proposal was to have a counter in the state which is up dated if we create a new instance so it will be an long living counter, which should be kept up to date.

> So let's say we reset it to 0 on every leader change. Is that so bad? Assuming this is a known limitation, of course. I guess one downside I see is if you had many long living processes - then you run into a similar problem, where it shows you have a small rate but really there's currently a ton of running processes.
> 
> Maybe keep some basic aggregates in the state itself isn't that bad? Number of process instances, number of jobs, number of deployed processes, etc. I don't expect this would have a huge impact on performance? Though it is one additional write per transaction in the worse case. I get that in itself it's not terrible, but every write most likely adds up over time. Although this isn't something public or anything, so we could always start with this and find a better solution.
> 
> You mention that this causes confusion - does it also cause us to make wrong assumptions and waste time?

In my opinion it is quite bad and confusing because this is often a metric people tend to look. Yes it is wasting time if it shows zero but actually it is 1 million running instances, which happens if a leader was restarted/fail over etc. Yes we see that the snapshot /state is big, but we don't know why. Is it because lot of variables in one instance? lot of jobs in one instance? Is is many instances? lot of messages? It would be really helpful to see kind of an estimate in the metrics to troubleshoot issues and help customers.

**Comment by npepinpe** [comment]
We'll go with just the rate for now and drop the accurate metrics, under the assumption we can see these in Operate. If we need them again we can add them at a later date.
