### ISSUE TITLE
Zeebe client deploy management

### ISSUE THREAD

**Issue by ezolnbl-dpc** [camunda-cloud/zeebe#4677]
**Is your feature request related to a problem? Please describe.**
I would like to gather information from a deployed bpmn so when the zeebe is exporting events to external places I could group related events to associate them with some kind of business logic like a tenant, customer, company, etc. Currently not all of the exported events(for example variable events) contains exact information from which I can tell what bpmn workflow executed this. Variable events contains these informations:
- workflowKey: 2251799813686314
- workflowInstanceKey: 2251799814175466
- scopeKey: 2251799814175466
From which I can't tell what is the source of this event.

Other solution would be to add meta information to the event before the broker calls export method, accessing deployments thru some kind of API internally or extend variable events (and every other kind of event where bpmnId is missing) with "bpmnProcessId" attribute.

**Describe the solution you'd like**
With the zeebe client one should be able to do actions on deployed bpmn workflows with workflowKey or workflowInstanceKey:
- query detailed info
- delete
- modify, for example reorder the version -> make an older deployed workflow higher in version order

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by npepinpe** [comment]
Hi @ezolnbl, when you send a deployment command, you get a deployment event back (e.g. Java API will be a `io.zeebe.client.api.response.DeploymentEvent`). This contains a list of `io.zeebe.client.api.response.Workflow`, which are the workflows that were deployed by that command. Each workflow includes the `workflowKey`, `bpmnProcessId`, and `version`. Using the workflow key, you can correlate most workflow related records.

For finer granularity, when you create a workflow instance, you can get the `workflowInstanceKey` from the response, and use this to correlate workflow related exported records.

Regarding the deletion, there's already an issue for it: https://github.com/zeebe-io/zeebe/issues/2908.

As for modifying, you could simply re-deploy the same older version, it will naturally become the latest version - note that migrating running workflow instances to other version is not yet possible, however.

If you're curious, you can look into tools like Operate and Simple Monitor, or even Zeeqs, to see how they aggregate the exported data to correlate all these things :slightly_smiling_face:

**Comment by ezolnbl** [comment]
Hi thanks for the answer. Listening for Deployment events could be a solution but when for example hundreds of events are firing to multiple exporters parallel and one of the newly deployed process (which's deployment information not yet arrived because it was deployed from another CI pipeline for example and the response must be synced between systems) instance's events does not contain any information which bpmnProcess sent it I have to manually store those events and later reprocess them when I finally know that specific "workflowInstanceKey" or "workflowKey" were originated from which bpmnProcess. 
The format of the process instance specific events are not generalized, some of them contains this, some of them contains that but not all of them contains bpmnProcessId as I said so I need manual steps to identify them and because the deployment/workflow API is very poor currently I can not do this just by waiting and storing events when eventually I will know which workflowKey identifies which bpmnProcess after a Deployment type of event arrives from exporters or from external sync from CI pipelines.

Let's say an event of this type arrives to me: (this is a kafka export)
```
{
    "partitionId": 1,
    "value": {
        "workflowKey": 2251799813686316,
        "workflowInstanceKey": 2251799814175408,
        "scopeKey": 2251799814175408,
        "name": "niceVariable",
        "value": {something},
    "sourceRecordPosition": 120263074432,
    "timestamp": 1591367911104,
    "position": 120263075056,
    "valueType": "VARIABLE",
    "recordType": "EVENT",
    "intent": "CREATED",
    "rejectionType": "NULL_VAL",
    "rejectionReason": "",
    "key": 2251799814175409
}
```

How would I know from that workflowKey or workflowInstanceKey (I don't know what is scopeKey good for...) which process execution created this event? There is no API internally or externally to identify it.

**Comment by npepinpe** [comment]
Sorry, this completely fell off my radar and I forgot about it. The `workflowKey` (now called `processKey` in 1.0) refers to the process definition, i.e. the BPMN model being executed. The `workflowInstanceKey` (now called `processInstanceKey` in 1.0) is the process instance being executed, so in that sense all the info is here, but you're correct that you need to aggregate it manually, which isn't great.

I'm happy to share that Camunda is considering building a query API for Zeebe to allow you to query these things though, so that should help a lot. It's still in early phases, but we're aware that it's important for users, so I'm sure it will come in the next 6-9 months.
