### ISSUE TITLE
Provide client query api for realtime status of instances/variables/jobs outside Zeebe worker.

### ISSUE THREAD

**Issue by TangJiong** [camunda-cloud/zeebe#5089]
**Is your feature request related to a problem? Please describe.**
Zeebe does provide a way to query workflow/instance/variables status from Elasticseatch, but **the biggest problem for me is the latency**.

* I read the elasticsearch exporter code and find that records are cached for some bulk seconds(default: 5s) before flushing to ES.
* What’s worse, records can’t be queried until they reach the ES refresh_interval(default 30s).

Thus, it cost a lot of time before we can query the real current status which is unacceptable in our production case as we have to feedback the current status of the instance/instance variables in minisecond-level latency for some service(not Zeebe Worker).

Though, we can reduce the bulk seconds and refresh_interval to smaller proper value, but it’s far from our goal.

**Describe the solution you'd like**
I wonder if it’s possible to export these event (aggregated status even better) to some in-memory storage and provide query api. In this way, we don’t have to change the Zeebe core architecture.

**Describe alternatives you've considered**

**Additional context**
I find zeebe-simple-monitor use hazelcast to store event and maintain status. Seems a possible solution? Since hazelcast provides in-memory storage and stream computation.

**Comment by saig0** [comment]
Hi @TangJiong,

thank you for raising this up. 

First of all, Zeebe doesn't provide a query API because this doesn't match with the underlying streaming architecture. It is basically a stream with a processor that processes commands and workflow events as fast as possible. In order to consume or query data, you should use the exporter API and store (and aggregate) the data in a format that fits your needs.

If this is your requirement:
> we have to feedback the current status of the instance/instance variables in minisecond-level latency for some service(not Zeebe Worker)

then exporters may not work for you. An exporter is more-or-less behind the actual workflow processing.

In order to understand your requirement better, please share more about the use case. What data do you need? What do you do with this data?

Maybe, the best and easiest option is to integrate the "notification" in the workflow itself.

**Comment by npepinpe** [comment]
I hope the above was sufficient for you :slightly_smiling_face: As there was no other activity since then, I will close the issue for now.
