### ISSUE TITLE
KryoException: java.nio.BufferUnderflowException Serialization trace: data (io.atomix.raft.zeebe.ZeebeEntry)

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#5495]
**Describe the bug**
Observed as error in production logs.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CO7t-Krt55OdUg?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2

**Comment by npepinpe** [comment]
The cause is Kryo attempting to deserialize an entry of length X, but the buffer containing the bytes to deserialize has length Y < X, and thus causes a buffer underflow. What the error message gives us is that it happens when attempting to deserialize the `data` field of a `ZeebeEntry`, which itself is a byte buffer. Could be an error in the serde of byte buffers (but then would occur more often, no?), or could be what's written on disk is corrupted. 

The impact is it causes the partition to transition to follower - the system eventually recovers as a new snapshot is received the log compact. You can see the node recover later on from the logs. However, in a single node/no replication set up, I imagine this would be problematic since no one will send you anything and there'd be no chance to recover.

In this particular instance, the error hasn't happened in almost two weeks, and as I mentioned, the node has recovered so we lost the data which could've caused this. We could investigate it if it occurs again.

**Comment by npepinpe** [comment]
I will close this for now as we've removed Kryo from our storage layer, and this hasn't reoccurred since.
