### ISSUE TITLE
Client should accept the job to send complete command

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#5763]
**Is your feature request related to a problem? Please describe.**

Currently in the java client we need to write:

```java
  client.newCompleteCommand(job.getKey()).send();
```

For me it is annoying to always write `.getKey()`. It should be clear that I want to complete that job the client can handle that also internally.

**Describe the solution you'd like**

I suggest that we overload the method and also accept the complete job.

```java
  client.newCompleteCommand(job).send();
```

**Describe alternatives you've considered**
Use c# client :wink: 

**Additional context**
...

**Comment by cobre420** [comment]
should this apply only to io.zeebe.client.api.worker.JobClient#newCompleteCommand(long) or other methods in the io.zeebe.client.api.worker.JobClient interface?

**Comment by saig0** [comment]
> should this apply only to io.zeebe.client.api.worker.JobClient#newCompleteCommand(long) or other methods in the io.zeebe.client.api.worker.JobClient interface?

Yes. I think it is best to be consistent so that all methods of the interface have the same signature.

**Comment by romansmirnov** [comment]
@npepinpe,

Besides the `JobClient`, in `ZeebeClient` another method exists that expects the job key: [`#newUpdateRetriesCommand(String jobKey)`](https://github.com/camunda-cloud/zeebe/blob/0e68d34196cad3d3acb2b84de8a9d2d8bbec86f2/clients/java/src/main/java/io/camunda/zeebe/client/ZeebeClient.java#L197)

Does it make sense from a user perspective to overload this method as well? So that there is an additional method that expects a (activated?) job, e.g. `#newUpdateRetriesCommand(ActivatedJob job)`.

**Comment by npepinpe** [comment]
Makes sense to me. It's useful to have a version which takes the minimum input (i.e. job key) and one which accepts the common case (i.e. job was activated and now I want to complete/fail/retry/etc.).
