### ISSUE TITLE
Readiness information for Broker is inaccurate

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#6134]
**Describe the bug**
The readiness information for Broker is inaccurate. It reports itself as being ready even before the startup procedure has finished. 

This led to an undiagnosed outage as part of https://docs.google.com/document/d/1ehhbUVFVsUEFIYpdBRg7MOTsJIVNxAZzKLjj2JKF2K0/edit?ts=600595cc. Here the nodes were crash looping because the startup took longer than the timeout, and Kubernetes could not detect that something was going wrong, because the Broker reported itself as ready.

**Expected behavior**
The Broker should include its startup state in calculating the readiness probe.

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.26.0
 - Configuration: Camunda Cloud (any cluster plan)

**Hints**
* The readiness probe for the broker is served by `MonitoringResultController`
* The value currently is based on `BrokerHealthCheckService::isBrokerReady` which essentially checks whether all partitions are installed

**Comment by npepinpe** [comment]
I thought about it, and what's missing here is what is the actual expected behaviour?

The problem that occurred is that in a single node cluster, the partitions were ready, but the processor had not been installed yet, and took too long (I think 5 minutes?), which meant the node was effectively "unavailable" for 5 minutes even though it was ready.

In a cluster with more replicas, however, this makes sense - it would probably start as a follower and as such wouldn't install any processor. If the whole cluster restarts, it might also start as a follower and then transition to leader once other nodes are up. So since the partition role may fluctuate, which isn't necessarily bad for a ready check - I'm just not sure what would be the consequences if we made the ready check DOWN when the stream processor a partition is not installed. It would prevent receiving traffic from outside - what happens if one partition is up (ready to receive traffic) but one isn't? Is the node ready or not?

I guess we need to think about it a little more.

**Comment by pihme** [comment]
What about `allPartitionsAreInstalled() &&  allStartupStepsHaveCompleted()`?

**Comment by npepinpe** [comment]
Would that have helped with this incident? I thought the issue was that it took too long to install the stream processor itself (I think 5 minutes to copy and open the snapshot?), which is tied to the partition role and not the start up steps. Or am I missing something?

**Comment by npepinpe** [comment]
After discussion, let's do this:

1. Implement a new startup probe (with endpoint) which is DOWN until the broker start up process has finished (i.e. all steps have successfully executed)
1. Have the ready probe endpoint simply reuse that startup, meaning that they are both essentially the same for now - this improves the situation for cases where the broker was ready but failed to startup within the given broker startup timeout (not to be confused with the k8s liveness probe or startup timeout), to make sure the kubelet knows that this node failed to startup correctly

We can work on a correct ready probe in the future, but it's already not behaving as it should, so the reasoning here is this doesn't make things worse for ready probe, and improves the situation for startup.

Let me know if you have any questions! Once this is done, please:

1. Document this change in the doc repo
1. Open an issue in the k8s controller repo to introduce a startup probe and use the correct endpoint for it (leave the ready as is for now, but then it's ready for us to later change it)

**Comment by deepthidevaki** [comment]
I can take up this issue. But I don't really understand what is the problem. @npepinpe @pihme Let's talk.

**Comment by npepinpe** [comment]
It's been a while, I guess I should've documented our discussion better. I'll need to re-read it and see what the issue is.

**Comment by deepthidevaki** [comment]
No worries. I talked with @pihme.

**Comment by deepthidevaki** [comment]
We added readiness probe to support safe rolling update. Once a node is started we want to wait until it is ready before the other nodes can be restarted. This way we can guarantee that there is always a majority (quorum) nodes available. We do not use readiness probe in the way it is expected. The docs says: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-startup-probe

> the existence of the readiness probe in the spec means that the Pod will start without receiving any traffic and only start receiving traffic after the probe starts succeeding.

This is not relevant for us because in our case gateway decides when to send a request to a broker. It is decided based on the topology. So readiness check has no use for us.

So I'm wondering if startup check is enough for us. Is startup check used by kubernetes in rolling restarts? 

If that is case we can add a startup check which is only true after all the steps in the startup phase is completed. https://github.com/camunda-cloud/zeebe/blob/cbb747838c11b7de6d83111fd32af16a8db0ca2c/broker/src/main/java/io/zeebe/broker/bootstrap/StartProcess.java#L51
This is independent of if the broker has leader or follower partitions. 

If startup probe is configured, the other probes - readiness and liveness - are executed only after startup is completed. Hence we can keep the current readiness check if we want.

**Comment by deepthidevaki** [comment]
I will go with the following solution:
1. Add a startup check which return true only after all startup steps are completed
2. Update ready check to additionally include the startup state. That means `ready = started && allPartitionsInstalled`

The reason for a different ready check is that the partition services are installed asynchronously. Hence they are not guaranteed to be installed when startup phase is completed. It is not yet clear if this ready check has any value for us. But I will keep it for now as it is not making the guarantees worse.

This would mean that the current systems (Kubernetes deployments) using ready check does not have to be changed. Later we can add startup probes in our Kubernetes deployments. At that time we can discuss if we want to keep this ready check or not.
@npepinpe @pihme wdyt?

**Comment by npepinpe** [comment]
Sounds good. Please open an issue on the controller side afterwards to let them know about this - I think this may also be something we can do ourselves, to be honest - just adding the startup probe definition.
