### ISSUE TITLE
Apply event-sourcing to the BPMN subprocess processor

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6195]
**Description**

* apply the event-sourcing concept to the BPMN subprocess processor

Reference:
* [ZEP: Create Workflow Instance](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#create-workflow-instance)

**Comment by Zelldon** [comment]
Lets do this together @korthout :smile:

**Comment by Zelldon** [comment]
We have some dependencies for multi instance, sub process and call activity for implicit end events, where will call the corresponding parent processors. https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/main/java/io/zeebe/[…]ngine/processing/bpmn/behavior/BpmnStateTransitionBehavior.java
I discussed with @Philipp Ossler this topic and made him aware of this. If we would make it clean we would need to migrate all processors at once, which is not really nice and scalable so we decided to just migrate the processors one by one, even if they have the dependency. This is possible because we have no tests with implicit end events Which brings me to the next topic. I would like to have tests for that. I will create separate issues for adding more tests for implicit end events and parallel gateway and I would like that we also improve the process generator, such that it is able to produce such processes.

**Comment by Zelldon** [comment]
> **CurrentBlocker** 
> I have the sub process marked as migrated. I need to active child instances, like the start event. If I use the command active element, this will not work since start event is not migrated. When I use the state writer then on normal processing the event is applied and creates a element instance. If we now do a restart the activiating of the start event is not applied, since the start event is not migrated. This means we will not create an element instance for it. This means also that the later processing failes, because of missing element instances etc.
> **Possible solution migrate start event**
> https://camunda.slack.com/archives/C01PCGQK2H2/p1616661991005700

> Talking about this https://github.com/camunda-cloud/zeebe/blob/zell-6195-sub-process/engine/src/main/[…]ngine/processing/bpmn/behavior/BpmnStateTransitionBehavior.java
> 
> Which is called here https://github.com/camunda-cloud/zeebe/blob/zell-6195-sub-process/engine/src/main/[…]zeebe/engine/processing/bpmn/container/SubProcessProcessor.java
> 

This actually means that all processors which uses this method are blocked by https://github.com/camunda-cloud/zeebe/issues/6184

This is the reason why I will migrate this first.
