### ISSUE TITLE
Cancel a workflow instance by writing a terminate command

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/zeebe#6199]
**Description**

* omit the cancel command when terminating a workflow instance
* instead, write a `TERMINATE_ELEMENT` command for the workflow instance 

Reference:
* [ZEP: Cancel Workflow Instance](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#cancel-workflow-instance)

**Comment by saig0** [comment]
This is not done yet. We're still writing a `cancel` command to cancel the process instance.

**Comment by Zelldon** [comment]
@saig0 just that I get it right. Do you mean you want to write the TERMINATE_ELEMENT by the clients? So no cancel command anymore? How do you fill it with all the needed details? This is currently done by the cancel processor afaik.

**Comment by npepinpe** [comment]
Sorry, that was on me, I figured it was done by writing the terminate command (but I did wonder why we did have a separate issue for something so small :sweat_smile:)

**Comment by Zelldon** [comment]
Discussed with @saig0 and we agreed on that it is not easy to do since we need details on the TERMINATE_ELEMENT to be able to process it by the BPMNElementProcessor, like ElementId, processDefinitionKey etc. These details are filled by the CancelCommandProcessor, the user command will only send the related processInstanceKey. For that reason we will close this for now
