### ISSUE TITLE
I can't activate a job with payload larger then maxMessageSize/2

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6207]
**Describe the bug**

Zeebe allows me to set a variable up to ~4 MB (maxMessageSize), but I can't activate a job with variables larger then ~2 MB (maxMessageSize/2). The reason for this is in the JobBatchProcessor which calculates the max batch size, which is much smaller then the real message size.  https://github.com/zeebe-io/zeebe/blob/develop/engine/src/main/java/io/zeebe/engine/processing/job/JobBatchActivateProcessor.java#L63

This is not obvious as a user, since the exception or incident message tells me that I should limit the variables such that I'm below 4 MB (maxMessageSize). https://github.com/zeebe-io/zeebe/blob/develop/engine/src/main/java/io/zeebe/engine/processing/job/JobBatchActivateProcessor.java#L234-L235

If I take a look at the code I understand the reason, but this feels like band aid on the problem. I think we should rework the job batch processing or what we write in the batch.

**To Reproduce**

* Create a cluster in camunda cloud
* Store the credentials in CamundaCloudMgmtAPI-Client-Test.txt
* Take the one_task.bpmn from the benchmarks.
Runt this script:
```sh
#!/bin/bash

set -exuo pipefail

source CamundaCloudMgmtAPI-Client-Test.txt
zbctl deploy one_task.bpmn

key=$(zbctl create instance benchmark | jq '.workflowInstanceKey')

randString=$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 1024; echo '')

for i in {1..3500}
do
  variables=$(jq -n --arg key "test-$i" \
    --arg var "$randString" \
    '.[$key] = $var')

  zbctl set variables "$key" --variables "$variables"
done

```

and try to activate a job. You will see an incident in operate. If you then try to limit the variables then it only works if you use 2000 variables (a 1024 bytes) not more.

**Expected behavior**
No incident and I can activate the job.

**Environment:**
 - OS: camunda cloud
 - Zeebe Version: 0.26.0
 - Configuration: [e.g. exporters etc.]

**Comment by npepinpe** [comment]
I would like to tackle the whole maxMessageSize stuff next quarter in general (if possible, or at least partially), and I think it probably makes sense to do this after the planned refactoring of the processors to not add more on the plate for now.

**Comment by npepinpe** [comment]
Unfortunately we didn't get around to it this time. I still want to tackle this at a more high level - max user message size (e.g. max input), how to deal with large messages internally (e.g. at the dispatcher level, at the log/replication level, etc.), but I haven't had time to think much about it. At the transport level, moving to gRPC will solve this issue so that's not a big problem. Similarly at the journal level we've also worked around this since we don't use intermediate buffers anymore.

**Comment by npepinpe** [comment]
This was actually fixed somewhat - the maximum batch length for job activation is actually not half, but only a little less than the maximum message size (essentially the maximum message size minus the record's metadata). So while it's not equal to the maximum message size, it's much closer than before.

This was fixed in https://github.com/camunda-cloud/zeebe/pull/5991, but it seems we didn't remove the limitation in the activate processor.
