### ISSUE TITLE
ZeebePartition doesn't handle exceptions properly

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6391]
**Describe the bug**

When I wanted to fix https://github.com/zeebe-io/zeebe/issues/6346 and introduced a new PartitionStep I realized that if the step would thrown an exception then the partition transition is actually not failed nor aborted. The exception is only catched in the actor scheduler which causes to call  https://github.com/zeebe-io/zeebe/blob/develop/util/src/main/java/io/zeebe/util/sched/Actor.java#L82, which prints `Uncaught exception in 'io.zeebe.broker.system.partitions.impl.PartitionTransitionTest$$Lambda$130/0x0000000800284840@79c7683a' in phase 'STARTED'. Continuing with next job.` This worries me a bit, since we leave the partition in a weird state. I would like that we handle exceptions better and abort the current transition for example (close resources etc.).

**To Reproduce**

Throw an exception in a PartitionStep

**Expected behavior**

Exception are similar handled then completeExceptionally

**Comment by MiguelPires** [comment]
PartitionSteps that take failure prone actions usually just wrap a try catch around those actions. Then the transition logic can just see if the future was completed exceptionally and act accordingly, which makes the transition code simpler and clearer. If we add more behavior to deal with exceptions outside, it makes the transition more complex and the PartitionStep contract less useful since we can't actually depend on it. Maybe we can just make it more explicit in the interface that exceptions should be caught and used to complete the future?

**Comment by Zelldon** [comment]
For me it is just that you move the complexity from point a to b, and reduce the duplication, since every step now needs to handle these potential cases. It would make it also more fault tolerant in my opinion if the transition can also handle exceptions from the steps, otherwise I see potential for real issues (inconsistent installed partitions etc.). BTW currently it means that the partition is stuck in the transition and will never complete it.

I see no big issue in adding a try-catch around https://github.com/zeebe-io/zeebe/blob/develop/broker/src/main/java/io/zeebe/broker/system/partitions/impl/PartitionTransitionImpl.java#L89-L100

Let me know what you think. We can also discuss this in the next triage meeting.

**Comment by npepinpe** [comment]
Refactor the next time we have to either refactor a step, or add a new step.

**Comment by MiguelPires** [comment]
closed by #6722
