### ISSUE TITLE
Support command to trigger a best-effort leader rebalancing

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#6437]
**Is your feature request related to a problem? Please describe.**

In case of an uneven leader balancing, for example after an major infrastructure problem, where most of the partition leaders are located one the same node/data center, the user might want to aim for a rebalancing of the leaders. This can help to reduce impact of a later infrastructure problem, where all/most partitions are effected by the fail-over.

**Describe the solution you'd like**

As an Zeebe operator I can send a command to the Zeebe gateway, which is broadcasted to the Zeebe brokers. The command should trigger a possible re-election of the partition leaders, to reach well balanced partition leaders. 

The preferred/prioritized leadership should be based on the affinity configuration (#6266), or in general on the initial balancing of the cluster if no affinity is given (#6265).

The result of the command cannot be guaranteed as we have to respect the guarantees of Raft, but should be on a best-effort basis and in a good situation lead to the desired effect of a well-balanced leadership. 

To be discussed:
- Should the command allow to specify specific partitions to balance
- Should the command allow to override/specify which broker should become leader for a partition

**Describe alternatives you've considered**

- A full restart of the system could help if we implement "Leader Balancing after startup" (#6265)
- We could implement a feature which would constantly tries to achieve a well balanced leadership, which might be tricky to get right, i.e. when to trigger, how often to trigger, which partitions to prefer, how to prevent constant negative impact on the running system

**Additional context**

***Note***: It has to be noted that every leader balancing will always have a operational impact, as an artificial fail-over is provoked which has at least a minimal impact on the corresponding partition processing.

**Comment by deepthidevaki** [comment]
I did a spike on this some time ago. Here is what  I did:

* RaftPartition exposes `stepDownIfNotPrimary`
* PartitionMetadata knows which member is primary
	* RoundRobinDistributor assigns the node with highest priority as primary
	* FixedDistributor also assigns the node with highest priority as primary
		* If priority is same for all nodes, a random node is assigned as primary. This would result in non-uniform distribution
* Leader balancing **rely on priority election**. If priority election is not enabled the results are unpredictable
	* *We can probably try to make it also work when priority election disables using anoint functionality. But this is not tested.*
* When stepDownIfnotPrimary is invoked, the node stepdown if it is not the designated primary node for this partition. This triggers a new election. When priority election is enabled the node with highest priority (=primary) will win the election with high probability and become the leader. If the primary is already the leader, then no new election is triggered.
* This works only on low load. The condition for a primary to get elected is that it has the latest log. On high load this is difficult to guarantee. But on low load the replication happens faster so that the primary node has a higher chance of having the latest log.
* In the spike the `balanceLeaders` api is exposed via BrokerAdminServiceEndpoint. This invokes `stepDownIfNotPrimary` on all partition on this broker. You have to send `balanceLeaders` command to each broker individually. This should be improved.
* **Tested and it works!**

**Comment by deepthidevaki** [comment]
TODO:

- [ ] #8223 
- [ ] #8224 
- [ ] #8222 
- [ ] #8225 

/cc @oleschoenburg

**Comment by oleschoenburg** [comment]
Two more issues then we are done:
* [ ] https://github.com/camunda-cloud/zeebe/issues/8341
* [ ] https://github.com/camunda-cloud/zeebe/issues/8340

**Comment by npepinpe** [comment]
Isn't this done?

**Comment by oleschoenburg** [comment]
Yes, it's done. Documentation here: https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/rebalancing/
