### ISSUE TITLE
Don't write Incident:Create command anymore

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#6528]
**Description**

Instead of writing Incident:Create commands, the processing of the record (on which the incident occurs) should write Incident:Created directly.

It might make sense to postpone this change until all processors that may raise an incident have already been migrated.

**Comment by npepinpe** [comment]
Your last sentence mentions we should do this until all other BPMN processors are migrated - does it make sense to already have this issue in the ready column then?

**Comment by korthout** [comment]
Haha, it's ready but blocked. Do we have a better way of dealing with this?

**Comment by npepinpe** [comment]
Ah, I see, I guess I wasn't clear on how the triage works now.

The ready column is for the next issues we should pick up immediately, i.e. you finish something, the next thing you pick up should come from the ready column.

The planned column is the immediate backlog, issues from this column are used to refill the ready column. The backlog is the same, but for the planned column (though ignore those atm since I haven't had time to really go through and move all the ones that should be in the backlog).

So for this right now, I'd move this issue to planned until we can work on it.
