### ISSUE TITLE
Request timeout logged at warning level

### ISSUE THREAD

**Issue by MiguelPires** [camunda-cloud/zeebe#6563]
**Description**

We see a lot of logs like:
```
Failed to activate jobs for type XYZ from partition X
java.util.concurrent.TimeoutException: Request type XYZ timed out in X milliseconds
	at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.timeout(AbstractClientConnection.java:163) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```
This is noisy and also causes users to assume there's a problem when there might be none. The timed out request is retried in another partition and usually resolves itself, so the log is neither actionable for an operator nor particularly useful for us. It might make sense to lower the log level so that we don't see this all the time and it doesn't mislead users. We can also log at a higher level if it can't be retried anymore (it's also propagated to the client).

**Comment by npepinpe** [comment]
Time outs are usually logged as warnings because they may be an indicator that something is wrong, but that it may resolve itself over time. In my opinion, if you have time outs all the time, there is clearly something wrong which should be investigated. Perhaps you've misconfigured your system, maybe there's not enough resources, maybe there's a bug somewhere.

Is the issue that users treat warnings as errors? Is our view of logs too developer-centric? How can we educate users of the difference between debug, info, warning, and error level?

**Comment by MiguelPires** [comment]
> Is the issue that users treat warnings as errors? 

At least in this case, yes. I also tried to get additional feedback as to what would've been more helpful in their situation but I haven't gotten an answer back. I think the distinction here is that seeing this log repeatedly is indicative of a problem but seeing it only occasionally is not. 
It's not a big deal, just something I noticed with one user. We can close it
