### ISSUE TITLE
Fix vulnerabilities for the Zeebe docker image

### ISSUE THREAD

**Issue by aivinog1** [camunda-cloud/zeebe#6599]
**Description**

As a user, if I run:
```
docker scan camunda/zeebe
```

I see a lot of vulnerabilities in the report. I expect to see no one vulnerability.

**Comment by npepinpe** [comment]
It seems like there are the following high vulnerabilities:

| NAME               | INSTALLED         | FIXED-IN              | VULNERABILITY        | SEVERITY
|----------------------|------------------------|--------------------------|------------------------------|----------------
| libc-bin              | 2.28-10                |                               | [CVE-2019-25013](https://nvd.nist.gov/vuln/detail/CVE-2019-25013)       | High
| libc6                  | 2.28-10                |                               | CVE-2019-25013       | High
| libgnutls30        | 3.6.7-4+deb10u6 |                               | [CVE-2021-20231](https://nvd.nist.gov/vuln/detail/CVE-2021-20231)       | High        
| libgnutls30        | 3.6.7-4+deb10u6 |                               | [CVE-2021-20232](https://nvd.nist.gov/vuln/detail/CVE-2021-20232)       | High

There are others with low score. I wouldn't focus on vulnerabilities with less than High severity imo.

In case you're curious, I used https://github.com/anchore/grype for this.

**Comment by npepinpe** [comment]
Having looked at these, I'm unsure if we're affected by them, at least to the severity reported. 

- The first one could cause a crash, but I fail to see how it could cause security issues as the containers would literally crash for us.
- The second and third ones, hm, I'm not 100% sure the JVM is linking against gnuTLS (unless it was statically linked?). When I run Zeebe and look at the pmap output, I don't see this library loaded by the process. I know for a fact the gateway will use BoringSSL via netty's tcnative library, so that only leaves the ElasticsearchExporter's httpclient, which uses standard Java SSL context. So from what I can tell gnuTLS isn't used by anything. In fact, removing it from the image has no impact on Zeebe. Of course if someone started another process which did use it, then possibly this could be a problem.

From my point of view, there's nothing we need to do here for now. I'm happy to discuss changing base images to ones updated more often, or having less security issues (e.g. going for distroless for example which would greatly reduce the surface of attack), but we can do this over Slack or the forums. However, if anyone has a concrete proposal, of course you can open an issue to detail it.
