### ISSUE TITLE
Enforce endianness in journal

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6669]
**Description**

While our serialization format uses little endian, anything using the mapped byte buffer that doesn't go through the SBE code is not - by default, I think it's all big endian. To be safe, we should simply specify `.order(ByteOrder.LITTLE_ENDIAN);` when mapping the buffer in `JournalSegment`. Probably make that a constant, a bit like we did for the protocol.

I thought about reusing the `Protocol.ENDIANNESS`, but it doesn't make sense for the journal to depend on the protocol module.

**Comment by shahamit** [comment]
@npepinpe @deepthidevaki - We are trying to deploy zeebe on s390x server that has BIG_ENDIAN byte ordering. We modified the Dockerfile to create s390x compatible image. 

While going through zeebe's code I understand that zeebe would work only on systems that have LITTLE_ENDIAN byte ordering. Can you please confirm if this understanding is accurate? Your confirmation would help me decide the next steps.
Thanks

**Comment by oleschoenburg** [comment]
@shahamit Interesting, I think the Zeebe team has little or no experience with architectures other than amd64 and arm64. Could you open a new issue to ask for compatibility with s390x or big endian in general? This issue here is old an only relevant to one component within Zeebe so I'd rather not re-open. Thank you!

**Comment by shahamit** [comment]
Sure I will create a github issue. I have tried starting a discussion by creating posts on the forum ([here](https://forum.camunda.io/t/zeebe-s390-architecture-support/46685) and [here](https://forum.camunda.io/t/bpmn-deployment-fails-on-s390x-server/47740)) but I didn't get any response. 

It would be great if someone from the dev team could do an analysis that zeebe in its current state won't work on s390x servers because its coded for little endian byte ordering. 

Thanks @oleschoenburg for the followup.
