### ISSUE TITLE
Replace usage of deferred records to keep track of sequence flow taken

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#6831]
**Description**

As part of #6827 and discussed in https://github.com/camunda-cloud/zeebe/pull/6827#discussion_r617220576, we might be able to reduce complexity of keeping track of taken sequence flows by simply storing the keys of taken sequence flows in state instead of storing the entire records using the deferred records logic.

**Comment by korthout** [comment]
I've tried to do this by storing the taken sequence flows in the element instance state as just another child of its flow scope. They can be removed on the element_activating of the target element. Fixing completions was relatively easy, by subtracting the `activeSequenceFlows` from `numberOfActiveElementInstances`. However, terminations are not as easy, because the taken sequence flow is not removed when that flow is interrupted. There is not really any event to describe the interruption of a flow as far as I can see. 

@saig0 @Zelldon Any ideas on how to approach this further?

**Comment by saig0** [comment]
I suggest implementing the parallel gateway merging logic as a first-class citizen. Instead of trying to reuse an existing construct, we build something specialized just for the merging logic (i.e. more explicit, clear in code, no interference with other parts).  

For example, introduce a new column for storing the taken sequence flows on a parallel gateway.

```
<flow scope key, element id of the gateway, element id of the sequence flow> -> number of taken sequence flows
```    

* On sequence flow taken, get and increment the counter. 
* If the counter of all incoming sequence flows is greater than 0 (using a prefix iteration with `<scope key, element id of the gateway>`) then activate the parallel gateway.
* Remove the entries if the gateway transition to activating, or if the flow scope transition to terminated.

@korthout what do you think?
