### ISSUE TITLE
Bulk request are deprecated

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#6868]
**Description**
Running a benchmark nowadays gives us endless logs of the elastic exporter which says that bulk request are deprecated. 

```
"request [POST http://elasticsearch-master:9200/_bulk] returned 1 warnings: [299 Elasticsearch-7.12.0-78722783c38caa25a70982b5b042074cde5d3b3a "[types removal] Specifying types in bulk requests is deprecated."]" 

```

Probably something we want to fix

Example
https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-04-26T09:35:48.785880000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-stackdriver%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-stackdriver%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0AjsonPayload.context.actor-name!%3D%22Broker-0-Exporter-3%22&scrollTimestamp=2021-04-26T09:33:50.113861000Z&pinnedLogId=m7cqp6g21p1lte&pinnedLogTimestamp=2021-04-26T09:33:50.113861Z

**Comment by korthout** [comment]
This relates to the removal of mapping types from ES: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html. 

Please correct me if I'm wrong. I'm not so familiar with ES. As I understand, we store records in a mapping type called `_bulk`. From there they are indexed into individual indexes. Since mapping types are deprecated in 7.x and removed in 8.x we should consider one of 2 options:
- create a new index for bulk as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html#_index_per_document_type)
- add a custom type field to mark entry as bulk as describe [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html#_custom_type_field)

**Comment by npepinpe** [comment]
It seems we also get warnings from using the legacy index template API. See [legacy](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates-v1.html) and [current](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html).
