### ISSUE TITLE
Ci current-test docker image blocks local development

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7249]
**Description**

I had several times in the past that I wanted to run IT test locally, which depend on a zeebe docker image with the tag `current-test`. This can happen for example if you run the golang IT tests, elasticsearch IT tests or upgrade tests. 

I'm wondering why we did it like this and whether it would be possible to reference the SNAPSHOT tag. I can image that can build at the begin the docker image with the SNAPSHOT tag (and not publish it) then use it in our IT tests (this should work since it uses it from the local registry) and then if all tests are green we can publish the tag (on develop only of course). 

With that we could still run the tests locally at least? This would make it easier to just run IT tests and reproduce issues like this: https://github.com/camunda-cloud/zeebe/issues/7161 

But maybe this doesn't make any sense :shrug: since normally you want to have you local changes in the build. Is there anyway we could improve here? I would like to not always build an docker image by hand before I can run these kind of tests.

**Comment by npepinpe** [comment]
See this proposal which addresses this to some extent - https://github.com/camunda-cloud/zeebe/issues/7241

We could use the `pre-integration-test` phase to build the image from the current build to ensure it's available. You can also then use the following properties to run your integration tests and set the default image to this: `zeebe.container.image` and `zeebe.container.version`. Then whenever you spawn a new `ZeebeContainer` (or variants), it will use that image. Since `pre-integration-test` phase runs after `package`, you would always have the latest distribution (barring the usual incremental compilation issues).

**Comment by Zelldon** [comment]
Would it help me in running this locally? especially with intellij? Which is my issue

**Comment by npepinpe** [comment]
Good point. We can check with TestContainers if the image exists or not, and build it. This may not work so well when using parallel mode (i.e. forking), but it should be fine for local development, and the image will already exist in CI so it should also be OK.

**Comment by npepinpe** [comment]
So I hacked it quickly, and it still wouldn't work 100% with intellij since our Dockerfile relies on the distribution tar ball being built, and intellij will not build that =/

**Comment by Zelldon** [comment]
we could also change the Dockerfile to build it as a separate step :D

**Comment by npepinpe** [comment]
So build the distribution in the Docker image? That might make it quite long though :sweat_smile:

**Comment by npepinpe** [comment]
I took a bit of slack time to come up with a prototype. See this draft PR: https://github.com/camunda-cloud/zeebe/pull/7338
