### ISSUE TITLE
Revisit backoffs and timeouts in raft leader appender

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#7364]
There is an [open bug on followers triggering unnecessary election](https://github.com/camunda-cloud/zeebe/issues/7175)
The main reason for this to happen is that the leader has a back-off mechanism that adds delay to the heartbeats. I would like to revisit these strategies and discuss if we can improve or get rid of any of them.

I would like to discuss the following points:

1. Back-off strategy that adds delay up to 60 seconds https://github.com/camunda-cloud/zeebe/blob/2579edc35b555bbeb2d8bb88ec557b024b82cb89/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java#L248-L260
1. Limiting the number of inflight requests https://github.com/camunda-cloud/zeebe/blob/1edfe4f762ef700885859bf87e1370963d3448a1/atomix/cluster/src/main/java/io/atomix/raft/cluster/impl/RaftMemberContext.java#L110-L116
1. Limiting the number of inflight heartbeats : https://github.com/camunda-cloud/zeebe/blob/1edfe4f762ef700885859bf87e1370963d3448a1/atomix/cluster/src/main/java/io/atomix/raft/cluster/impl/RaftMemberContext.java#L123-L125
1. Timeout for raft requests
1. Timeout for leader step down when there is no quorum https://github.com/camunda-cloud/zeebe/blob/2579edc35b555bbeb2d8bb88ec557b024b82cb89/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderAppender.java#L168-L172

#### Details
1. Back-off strategy that adds delay up to 60 seconds.
There are additional mechanisms such as limiting the number of inflight requests to prevent a leader from bombarding a follower with requests. Isn't that enough? Do we need another back-off on top of that?
If this back-off is useful, the delay should be less than election timeout. A leader should send a heartbeat at least once with in an election timeout, otherwise the follower can trigger an unnecessary election.

1. Limiting the number of inflight requests 
This is useful in my opinion. But we should revisit if the current strategy is optimal. 

1. Limiting the number of inflight heartbeats
Currently the inflight heartbeats can be only 1. While having some limit on the inflight heartbeat is useful not to overwhelm a slow flower, a limit of 1 seems to be too low. This is even more problematic due to the high timeout for raft requests as described below.

1. Timeout configured for raft requests
The default timeout is 5 seconds, which is greater than the election timeouts. I think this is a bigger problem. All the above back-off strategies are based on the failures which are detected based on the timeouts. If a heartbeat is send, it takes 5 seconds to timeout in case of any failures. So no heartbeat is send to this follower during this 5 seconds. This time is enough for a follower to trigger an unnecessary election.

1. Timeout for leader step down when there is no quorum is also too low compared to the configured request timeouts.
I think this is also not an optimal value. The request timeout is 5 seconds, while the timeout for the leader to step down is also 5 seconds (2 * election timeout). Thus a temporary disconnection can cause a leader to easily step down, which may be unnecessary. 

Ideally, a leader should send a heartbeat at least once with in an election timeout period. But at the same time, we have to ensure that the leader is not overwhelming an already slow follower by continuously sending messages.

I'm creating this issue to discuss these points. Feel free to add comments, questions or ideas to improve the situation.
@npepinpe @Zelldon :eyes:

**Comment by npepinpe** [comment]
My thoughts on the above:

1. We should throttle how many requests we send to a follower, but you're right that backoff is the wrong approach here. What we want is to establish flow control between the two nodes, and typically the consumer (in this case, the follower) is the one who controls this. That's a bit of a bigger undertaking however, but we could start with simply sending a regular, conservative rate, and can extend this in the future where the follower can reply with its acks (since all Raft requests have acks) how much you can send it next. But definitely we can drop the back off I think and go for a conservative fixed (but configurable) amount.
2. See above.
3. Normally, heartbeats are one-way only - they're meant to tell another node that we're still alive. Here we use it kind of two way - we also use it to detect when we don't receive an ack, and suspect a network partition. I would challenge if this is necessary, or if using a standard heartbeat approach is fine. After all, heartbeats are really only used when we have little to no load, otherwise we're sending real appends which do have acks. Is it necessary, on low load, for the leader to detect if a follower is not receiving its heartbeats? How useful is that? If we decide not, then here it's really just sending a ping every once in a while, and I'd be happy to reevaluate a way that we could fire and forget these on the leader without having to fear overwhelming the follower.
4. Agreed. I'm a bit worried about the context propagation - cancelling a request locally doesn't mean the remote node is aware of it, and then you can potentially more easily overwhelm it if your timeout is quite low. But definitely it should be based on the election time out I think.
5. Agreed. I'm still unsure how useful that part is, but happy to hear about it.

**Comment by deepthidevaki** [comment]
>     5. Agreed. I'm still unsure how useful that part is, but happy to hear about it.

Do you mean why should the leader step down? This is required to guarantee liveness during **partial** network failures. TLDR:- There are cases where no new leader cannot be elected because the current leader is up,  but the current leader cannot reach the quorum and thus not able to make progress. You can read more about it [here](https://decentralizedthoughts.github.io/2020-12-12-raft-liveness-full-omission/) We also had a slack discussion about this topic some time ago, but I can't find it anymore.

**Comment by deepthidevaki** [comment]
> Normally, heartbeats are one-way only - they're meant to tell another node that we're still alive. Here we use it kind of two way - we also use it to detect when we don't receive an ack, and suspect a network partition. I would challenge if this is necessary, or if using a standard heartbeat approach is fine. After all, heartbeats are really only used when we have little to no load, otherwise we're sending real appends which do have acks. Is it necessary, on low load, for the leader to detect if a follower is not receiving its heartbeats? How useful is that? If we decide not, then here it's really just sending a ping every once in a while, and I'd be happy to reevaluate a way that we could fire and forget these on the leader without having to fear overwhelming the follower.

I don't think it is a good idea to remove ack from heartbeats.
* Ack for hearbeats are way for the leader to know that it is still connected to a quorum of followers. To know why is it important for the leader to know that the followers are not connected, see my comment above. 
* Second, the heartbeats are not sent only in low load. During normal load, if a leader detects a follower failure, it switches to sending heartbeats instead of replicating the events. There is no point in sending the events if the follower is not receiving it. Once the follower restarts to acknowledge, the leader switch to sending the events again. The ack to heartbeats also tells if the follower is lagging behind and if the leader should send old events from the log. 

Btw, original raft paper also uses empty AppendRequests as heartbeats. There are no special heartbeat messages without ack.

**Comment by deepthidevaki** [comment]
> Agreed. I'm a bit worried about the context propagation - cancelling a request locally doesn't mean the remote node is aware of it, and then you can potentially more easily overwhelm it if your timeout is quite low. But definitely it should be based on the election time out I think.

That is true. We might need to find some other approach on the receiver to drop requests when it is overwhelmed.

**Comment by deepthidevaki** [comment]
> 1.We should throttle how many requests we send to a follower, but you're right that backoff is the wrong approach here. What we want is to establish flow control between the two nodes, and typically the consumer (in this case, the follower) is the one who controls this. That's a bit of a bigger undertaking however, but we could start with simply sending a regular, conservative rate, and can extend this in the future where the follower can reply with its acks (since all Raft requests have acks) how much you can send it next. But definitely we can drop the back off I think and go for a conservative fixed (but configurable) amount.

My idea was to drop this back-off and rely on the configured inflight requests (from item 2 and 3). Of course we have to find out optimal values for them. maxAppendsPerBroker is already configurable.

**Comment by Zelldon** [comment]
> Back-off strategy that adds delay up to 60 seconds.
There are additional mechanisms such as limiting the number of inflight requests to prevent a leader from bombarding a follower with requests. Isn't that enough? Do we need another back-off on top of that?
If this back-off is useful, the delay should be less than election timeout. A leader should send a heartbeat at least once with in an election timeout, otherwise the follower can trigger an unnecessary election.

As you know I agree with this. I don't think we need this.

**Comment by Zelldon** [comment]
> Timeout configured for raft requests
The default timeout is 5 seconds, which is greater than the election timeouts. I think this is a bigger problem. All the above back-off strategies are based on the failures which are detected based on the timeouts. If a heartbeat is send, it takes 5 seconds to timeout in case of any failures. So no heartbeat is send to this follower during this 5 seconds. This time is enough for a follower to trigger an unnecessary election.

I agree. In general we should revisit all these timeouts and find better values for it.

**Comment by deepthidevaki** [comment]
Btw, electionTimeout, heartbeatInterval, requestTimeout, minStepDownFailureCount and maxQuorumResponseTime are already configurable (PR open). So we can also evaluate different values.

**Comment by npepinpe** [comment]
We did do some work related to this - is there anything more you'd like to do here? I will close it for now, but please reopen if you'd like to continue with other things, or create new, more concrete issues.
