### ISSUE TITLE
Remove dependency to SnapshotStoreSupplier in partitions

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7409]
Currently the dependency to `SnapShotStoreSupplier` is a bit unwieldy. The supplier is created very early and globally.
After refactoring the bootstrapping, the snapshot store will be created alongside the partition.

As an intermediate step, the goal of this issue is to remove the dependency to `SnapshotStoreSupplier` from the partition. This class is only used in the transition. It is used in several ways:

`ConstructableSnapshotStore getConstructableSnapshotStore(int partitionId);` and `ReceivableSnapshotStore getReceivableSnapshotStore(final int partitionId);` are passed on into `StateControllerImpl`

The method `PersistedSnapshotStore getPersistedSnapshotStore(int partitionId);` is used by several callers to eventually register a snapshot listener.

Therefore, to reduce the dependencies:
* the method `PartitionTransitionContext#getSnapshotStoreSupplier()` will be removed.
* two new methods will be added to `PartitionTransitionContext`
  * `getConstructableSnapshotStore()`
  * `getReceivableSnapshotStore()`
*  `LogDeletionService` will use `getReceivableSmapshotStore()` _and_ `getConstructableSmapshotStore()` instead to register itself as listener (it's currently the same object, but there is a set, so it should be fine. If these ever are two objects, my thought is that we want to compact the log regardless of who created the snapshot)
* `LeaderPostStoragePartitionStep` and `ZeebeDbPartitionStep` will use `getConstructableSnapshotStore()` instead to register itself as listener (with the rationale, that in this case the newly created snapshot shall be replicated)

**Comment by pihme** [comment]
@Zelldon Could you please review this issue whether you are ok with the proposed changes?

**Comment by Zelldon** [comment]
tbh. It is a bit hard for me to follow this description. It has been a while since I had a look at it, but what I would like to point out is that the receivable snapshot store is only used on follower side. Idk whether it makes a difference for you. 

Another note: LeaderPostStoragePartitionStep will register for replicating snapshots, which will be not necessary after building state on followers.

Other than that I think it is fine. What ever you makes you happy do it. I think we can discuss it also if you create an PR, currently it is a bit hard to reason about.
