### ISSUE TITLE
Follower reaction on install request

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7481]
**Description**

When building state on followers one interesting part is the handling of install requests, from the leader. In the POC https://github.com/camunda-cloud/zeebe/issues/7328 we caused a transition to follower again, which should reinstall/reinit all needed services. This is also described in our ZEP https://github.com/zeebe-io/enhancements/blob/master/ZEP007-build-state-on-followers.md.

We can implement it like this again and should investigate whether we get any problems regarding race conditions etc. If this is the case we might need a different solution. It might make sense in general to think about what could be an alternative look like.

At the end we should find a way to react on installRequest, which allows us to re-init our dependencies.

Blocked by #7480 
Blocked by #7457

**Comment by Zelldon** [comment]
> We can implement it like this again and should investigate whether we get any problems regarding race conditions etc. If this is the case we might need a different solution. It might make sense in general to think about what could be an alternative look like.

It might make sense to really handle it as an special case, which means it needs a special solution. One thing I can think of (was also part of our discussions) is to introduce new listeners, which are called after the complete snapshot has been received before the log is truncated and afterwards. 

Example interface:

```java
public interface ResetLogListener {

  /** should be used to close/pause all consumers of the log **/
  void beforeLogReset();

  /** should be used to reopen/resume all consumers of the log, here we can start to restore our state **/
  void afterLogReset();
}
```

We could close the stream processor, exporters etc on `beforeLogReset`, then the FollowerRole, will reset the log completely and call `afterLogReset` Here we can open the recent snapshot and restore the DB, which means reopening stream processor etc.

**Comment by deepthidevaki** [comment]
> The question is do we care if something fails between, e.g. if we reset the log and some readers get issues? Is it really an issue, since they anyway recreated soon.

These asynchronous reactions can cause some issues. It doesn't lead to inconsistencies, but can lead to unnecessary noise in the logs. Consider the following case:
1. Log resets
2. StreamProcessor is still reading the log (it has not reset its state to new snapshot)
3. It reads the next event after the log is reset, that means it is skipping some events.
4. StreamProcessor replays the event. There might not be a corresponding instance in the state. What will be the result? Does the StreamProcessor goes into an error loop because such an error is not expected during a replay? 

This does not lead to an inconsistent state, as the transition happens later, and the state will be reset to the new snapshot and replay restarts from the snapshot position. But there will be an intermediate period where StreamProcessor is in an invalid state, and might log errors or blacklist instances which can cause confusion. 

This would be the case for both listener approach or transition approach mentioned in the above commend. In both approaches, we cannot block raft thread until StreamProcessor reacts to the reset.

**Comment by deepthidevaki** [comment]
There is also a previously unnoticed issue.
It is a problem if the StreamProcessor reads too early. Consider the following case:
1. Follower received new snapshot
2. Reset the log (throw away everything, log is now empty)
3. StreamProcessor is reset with the new snapshot.
4. StreamProcessor seek to the snapshotPosition, but the log is still empty as the follower did not yet receive the next event after receiving the snapshot. In this case, I assume, StreamProcessor crashes as it cannot find the event to start replaying. If it does not crash, it can lead to an inconsistent state. 

Another scenario:
```
    State on Leader:                             
                                                     
        Log:                                         
        ------------------------------------         
        | 10  | 12 |  13 | 14 | 15 |  16|      
        ------------------------------------         
           ^                    ^                    
           |                    |                    
        Exporter              Processor              
        Position              Position               
                                                     
        Snapshot = 10-10-15 (index-exporter-processor) 
 ```       

1. Follower receives new snapshot 10-10-15
1. Reset log
1. Reset StreamProcessor
1. Received events 10 and 11

```
    State on Follower:                          
                                                     
         Snapshot = 10-10-15                               
                                                     
         Log:                                        
         --------------------                        
         |10 |11 |                            
         --------------------                        
 ```                                                  
 
5. StreamProcessor recovering from new snapshot
6. StreamProcessor attempts to replay events => Seek to snapshotPosition (15) => Fails!

**Comment by deepthidevaki** [comment]
> StreamProcessor seek to the snapshotPosition, but the log is still empty as the follower did not yet receive the next event after receiving the snapshot. In this case, I assume, StreamProcessor crashes as it cannot find the event to start replaying. If it does not crash, it can lead to an inconsistent state.

Just verified. Processor does not crash. It just assumes it has seeked to the right position and continue replaying. When we replay events, we are checking if it's source position > snapshotposition so as not to reapply the event. So it should be safe to not wait until the event at snapshotposition is available in the log. Should also check how it affects taking snapshots on the follower.

**Comment by deepthidevaki** [comment]
> The question is do we care if something fails between, e.g. if we reset the log and some readers get issues? Is it really an issue, since they anyway recreated soon.

There is also a small chance the the reader has still references to an unmapped segment which can cause segmentation fault. For this reason, I would prefer to go with the listener approach than the transition. The listeners can implement the transition steps - that is `beforeLogReset` closes all follower services, `afterLogReset` re-install all follower services.  In addition, I think it would be better to trigger `beforeLogReset` when the first InstallRequest is received. If the before and after listeners are called when we reset the log, there is not enough time for the StreamProcessor to react before the log is reset. That means, it is still trying to read from the log while it is deleted. Although most concurrent access is handled, it can lead to segmentation fault if the unmapped segment is accessed by the reader. Hence to give enough time for the StreamProcessor to close before the log is reset, we should call `beforeLogReset` when the first chunk of the snapshot is received and `afterLogReset` is called after the log is reset. This is still not fully safe. We are assuming that the reader are closed before we reset the log because there is enough time to react.  
To make it fully safe, we should ensure that the segment that is deleted is not unmapped until all references to that segment is removed. I would say that we will first implement the above simple solution, and can investigate how to improve the safe access to the log while it is deleted. Ideally the followers shouldn't receive InstallRequest very often.
