### ISSUE TITLE
Extract PartitionService from Atomix

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe#7535]
**Description**

Goal of this issue is to extract the `PartitionService` from the `Atomix` class.

The steps have already been attempted in https://github.com/camunda-cloud/zeebe/pull/7381 (except for refactoring tests)

Out of scope for this issue is to change the way partitions are created and registered. This will be changed in a later issue.

**Implementation Steps** 
* Crreate new class `PartitionManager`
* Move logic that deals with `PartitionService` from `Atomix` to `PartitionManager`
* Adjust `AtomixFacotry, AtomixBuilder. AtomixConfig, AtomixRule`
* Remove `PartitionService` from `ClusterServcies`
* Create `PartitionManager` in `Broker#partitionsStep`
* Create `SnapshotStoreFactory` in `Broker#partitionStep`
* Refactor test classes

**Comment by npepinpe** [comment]
I've been thinking more about what we discussed regarding the PartitionManager, and how it could be used as a facade for all nodes in the cluster which need to write to a partition (whether locally or remotely).

Generally, all nodes (potentially) want to write to a partition - the gateway wants to execute commands (and receive the response), and the brokers want to write arbitrary records: this means leader of partition A writes command `Message.CORRELATE` to leader of partition B, and leader of partition B answers by writing an _event_ to the leader of partition A (e.g. `Message.CORRELATED`). 

Additionally, some nodes (mostly the gateways) want to know the status of the partition - which brokers belong to it, who is leader, who is follower, it's health status, etc. I think the brokers don't care about this other than who is leader (so they can write to it).

So we could have something like `partitionManager.getPartition(1).execute(command)`, which returns the response async, and `partitionManager.getPartition(1).write(record)`, which just returns whether it was written or an error async. And additionally you'd need `partitionManager.getPartition(1)` to return some object which can tell you something like `#getMembers()/#getLeader()/#getFollowers()` or some such (or if we change the wording, `#getPrimary()/#getBackups()` or whatever it is - potentially you don't really need the `#getBackups()` I guess).

What I'm getting at here, is that right now you build the list of known partitions differently based on the node type. Brokers have a static partition distribution - they know that there are X brokers in the cluster, they know the number of partitions, and the replication factor, and can just compute where each partitions are, so they can already build a list of local and remote partitions at bootstrap time. Gateways, on the other hand, discover partitions via the topology, so their set of partitions is mutable. One thing we could challenge here is if it wouldn't make sense for the gateway to also know the cluster topology in advance - that would make it easier to deal with bootstrapping, and would also improve the quality of the start up/ready/liveness probes. That's a breaking change unfortunately (AFAIK), so may not be viable. That means we may need a mutable partition manager, or at least mutable _discovery/distribution_.

That said, this won't be done in the scope of this milestone (since there's not much point in doing the gateway part before we refactor the transport/merge the command API with the other inter partition APIs), but it probably will influence the bootstrapping of the manager I think.
