### ISSUE TITLE
Spike: learn how to support custom client command authorization

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#7551]
**Description**

We want to perform a spike to find the answers to the following questions regarding the custom client command authorization #7490. 

Most questions are related to the **temporary** Query API, which will allow the custom gRPC interceptors to retrieve the relevant data necessary to perform the authorization.

**Questions that should be answered after the spike**
- [x] what should the Query API look like, e.g. should it be similar to the Command API or can it be simpler?
- [x] the Query API should be easy to remove, so how to keep it self-contained with the least invasion on existing code?
- [x] how can the broker Query API gain access to the state?
- [x] what will the Query API server look like?
- [x] how to best place this Query API behind a feature toggle?
- [ ] what should the interface to the Query API look like from within the interceptors?
- [x] how to best allow users to provide custom gRPC interceptors?

**How to approach the spike**

To answer the above questions, we want to take the following steps:

- [x] play around with the Command API to learn how it works
- [x] add a Query API next to Command API
- [x] provide access to the state from the Query API, try to provide as little as possible processing access to the Query API, perfect is only the immutable state classes
- [x] consider ideas on how to place the Query API behind a feature toggle
- [x] read up on gRPC interceptors
- [ ] build a simple interface to the Query API that is available to the interceptors
- [ ] test it by building a simple interceptor (directly in the gateway) that uses the Query API to retrieve some information
- [x] consider how to best allow users to provide custom interceptors

**Comment by korthout** [comment]
Notes about the Broker's Command API:

```
Command API receives commands over Atomix transport, AKA server transport.
CommandApiService registers the request handler to the server transport.
CommandApiRequestHandler can handle requests.
Before handling any request it drains a command queue (these are not requests, but internal commands, e.g. when disk space becomes available it needs to set a flag).
Requests contain SBE messages, for which a version and template id are verified.
The version check makes sure newer client's can't send messages of versions the request handler can't deal with yet.
The request handler also provides back pressure (e.g. out of disk space).
If everything is okay, it writes a command build from the message to log stream.
The SBE messages are generated from the SBE protocol.
```

**Comment by korthout** [comment]
How to separate the Query API from the Command API?

I currently see multiple options to achieve this:
1. we could spin up a separate QueryApiService that binds a new transport server to a different port on the same host
2. we can use different topic name, such that the transport server uses the QueryApiRequestHandler or the CommandApiRequestHandler
3. we can use 1 ApiRequestHandler and specifically look at the message that was sent in to determine it.

There are pros and cons for each of these options. For now, I think it's easiest to go for 2 and use the topic names to distinguish between the two. At this time, the only downside for option 2 that I see is that it binds having multiple request handlers to a transport implementation that supports topic names.

**Comment by korthout** [comment]
I think we can answer some first questions:
>what should the Query API look like, e.g. should it be similar to the Command API or can it be simpler?

It can be a bit simpler, because we only need a request handler subscribed to a different topic name.

>the Query API should be easy to remove, so how to keep it self-contained with the least invasion on existing code?

By utilizing the topic name, the only other addition is some kind of mapping in the gateway that makes sure to set the topic name for command api requests differently from query api requests. In the gateway it should then be easy to remove the query api code, and in the broker we only need to remove the query api request handler. The rest can keep working as it was.

>what will the Query API server look like?

We don't need a special server, we can just use the Command API server. We can consider renaming this server, but note that there also exist config options for this (e.g. network.commandApiCfg).

**Comment by korthout** [comment]
> How can the broker Query API gain access to the state?

The Command API gains access to the log stream because it is a PartitionListener, which means the Command API is informed when the broker becomes leader for a specific partition. When that happens the log stream is provided along as a parameter of the callback to the listener. 

However, this strategy is deprecated, due to the current refactoring of the bootstrapping (see [Refactor Bootstrapping Milestone](https://github.com/camunda-cloud/zeebe/milestone/61)).

A new way to access partition specific APIs will be provided as part of this refactoring. Potentially something like `partitionManager.getPartition(partitionId).getLogStreamWriter()` to provide a log stream writer which can be used by the command api. Similarly, something like this can be imagined for the ImmutableZeebeState needed by the Query API.

For the continuation of the spike, we can simply assume that this will be the approach we take. And while this is not yet available, we can use the deprecated PartitionListener strategy to at least have a way to access state from the Query API.

**Comment by pihme** [comment]
Hi Nico,

as we discussed I write a couple of comments to ease handover. Most relevant to you is this branch `7551-nico-handover-draft-interfaces` which contains a preview of the interfaces as last discussed with @npepinpe.

Please also look at the documentation in https://docs.google.com/document/d/1yP9kv21H18Esd5LLc7O1sW04rlk20mf8I0TuJAsi3qU/edit# where I am going to talk more about the concept as it stands today. (or I won't if my internet is cutting out again :-( In that case just ask Nicolas)

For a more complete preview of the interfaces you can also check out: https://github.com/camunda-cloud/zeebe/pull/7594

The difference between this draft and the branch mentioned above is that the branch above is more tailored to what you will probably need next, and the branch above has some skeleton implementation for the partition manager.

There is one big caveat to all this: Nicolas and I discussed these interfaces about a week ago. Afterwards we had some more intense discussion on the question of how much we want to commit to the actor model as architectural paradigm. This discussion resulted in the decision to commit to the actor model and gradually move towards it. 

I mention this because the interfaces were drafted before that and there might be changes necessary to better align it with actor style programming. I would like to refer you to Nicolas in this regard.

The long term vision is that the gateway will also have a partition manager which gives you access to _ClusterParitions_, which are the location-independent representation of a partition. So then the gateway would use the partition manager to acquire a cluster partition, get its query interface. Then the cluster partition would internally figure out on which node the partition lives and forward the query to that node, then that node would use the partition manager to get the local partition and execute the query.

However, in Q3 it is very unlikely that the gateway will have access to the partition manager as the refactoring is currently focused on the Broker. I am afraid you have to find a different way to get from the gateway to the right node, for a time being.

**Comment by korthout** [comment]
>how to best allow users to provide custom gRPC interceptors?

Generally, we can use a similar approach to the exporters where users define a jarPath to a jar containing their custom interceptor. What I'm specifically wondering about is what interface they should implement. 

1) There's something to say to allowing users to simply implement `io.grpc.ServerInterceptor`, but this would bind this part to our gateway protocol. It also means that users must be familiar with how this interceptor works. Looking at https://github.com/grpc/grpc-java/blob/v1.40.1/examples/example-jwt-auth/src/main/java/io/grpc/examples/jwtauth/JwtServerInterceptor.java there are some intricacies to keep in mind.

2) Another idea is to let them implement our own defined interface and map the `io.grpc.ServerCall` (and related interfaces like `io.grpc.ServerCallHandler` and `io.grpc.ServerCall$Listener`) to our defined interface for this. The benefit would be that we are not fully bound to grpc as the gateway protocol, but changing it still requires us to find mappings to all ServerCall properties which might be difficult.

3) A third option could be to restrict intercepting only to this custom authorization topic. The interface could then be specialized to `AuthorizationInterceptor` or so. Benefits would be that the interface can be smaller and might even be removed again with the query api. The main argument against this, is that it is not flexible and cannot be used for other use cases.

@npepinpe which option has your preference? Or do you see any options, I've missed here. My personal preference leans towards the first option, because I think our gateway protocol choice is stable, but you may have another view on this.

1. users can implement `io.grpc.ServerInterceptor`
2. users can implement `io.camunda.zeebe.gateway.Interceptor`
3. users can implement `io.camunda.zeebe.gateway.auth.Interceptor`

**Comment by npepinpe** [comment]
Regarding loading of interceptors, I would still want to be able to load isolated JARs to avoid dependency collision, but maybe we could think of doing https://github.com/camunda-cloud/zeebe/issues/7628 first (or similar) to properly allow embedding the configuration of their interceptors?

Regarding the interface choice, I don't think we need to plan on moving away from gRPC any time before 2.0 (which, who knows when that will be). There could be some concern of tying users to this interface if we expected versioning issues with the gRPC library, but I think this is unlikely. Allowing users to load arbitrary `ServerInterceptor` will also increase the interoperability of our gateway with the general gRPC ecosystem - if we add a layer of indirection, then users would always have to wrap existing interceptors with an adapter (now this might be necessary regardless because of configuration issues, of course - not every existing interceptor is necessarily a bean :smile:).

So from my point of view, I think the downsides of having users implement `io.grpc.ServerInterceptor` are minimal - I don't think we would move away from gRPC until 2.0, and it would be a major breaking change requiring completely new clients as well. The only downside I see is if we think the interface (and dependent types from the library) are unstable.

Downsides of introducing our own set of types are bigger I think - we don't know what the right API would be (as opposed to the gRPC team which has had more time to figure that out), it's more stuff to maintain (both in terms of code and documentation), it adds more indirection to the system (I imagine it would be fairly straight forward, but any subtlety could be quite surprising :smile:), it makes error handling potentially unnecessarily complex (will users throw exceptions? return gRPC codes? are we mapping their exceptions to gRPC codes?).

Regarding introducing authentication specific interfaces, I think you already summed up the main issues, which is not being able to load anything non-authenticated related (e.g. observability interceptors such as distributed tracing, logging, metadata enriching, analytics, etc.)

I would start simple and just implement the gRPC types, but I'm happy to hear more about it - I'm just not yet convinced that we need more indirection :smile:

**Comment by korthout** [comment]
Since we started the implementation, I'll close this issue
