### ISSUE TITLE
Java client is returning null instead of empty objects

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/zeebe#7630]
**Describe the bug**

We have several commands which should return an empty response like:

 * Fail job
 * Complete job
 * Cancel instance
 * Resolve incident 
 * etc. 
 
But instead of returning an object (which would be expected, since it is part of the interface) it is returning null.

The following fails:
```java
val failResponse = zeebeClient.newFailCommand(job.key)
            .retries(0)
            .errorMessage("This failed oops.")
            .send()
            .join()

assertThat(failResponse).isNotNull // fails
```

In C# we return an empty object instead, https://github.com/camunda-community-hub/zeebe-client-csharp/blob/master/Client/Impl/Commands/CompleteJobCommand.cs#L53

**To Reproduce**

The problem is in the `RetriableClientFutureImpl`, if there is no response mapper given then it will return null.

**Expected behavior**

An empty object and not null. 

**Environment:**
 - OS: all
 - Zeebe Version: 1.0.0+ 
 - Configuration: all

**Comment by shreelakshmijoshi** [comment]
Hi @Zelldon !
I am a new open source contributor and would love to solve this issue, could you help me understand the issue better by providing some extra references ? 
Is this is issue open to contribute ?

**Comment by saig0** [comment]
@shreelakshmijoshi yes, we're happy to receive contributions :heart: Feel free to contribute by creating a PR :rocket: 

Make sure to have read our [contribution guide](https://github.com/camunda-cloud/zeebe/blob/develop/CONTRIBUTING.md).

---

**Context**
The issue is located in Zeebe's Java client. The client can send several commands. If the caller waits for the response by using `.send().join()` then it retrieves the response. In some cases, as described in the issue above, the client returns `null` as a response. Instead, it should return a response object as it is defined in the interface. Even if the response object doesn't have a property/field.

Implementation-wise you can compare `io.camunda.zeebe.client.impl.command.CreateProcessInstanceCommandImpl` that returns a response with `io.camunda.zeebe.client.impl.command.CompleteJobCommandImpl`. The difference is in the `send()` method.

**Comment by tulikavijay** [comment]
@saig0 I don't see a PR, may I work on this

**Comment by saig0** [comment]
@tulikavijay I'm not aware of this failure. The build should work if you use Java 11.

**Comment by tulikavijay** [comment]
@alexanderavdeev14 pls go ahead. I am not able to build it locally, seems like there seems to be some mismatch with jvm.

**Comment by npepinpe** [comment]
We're in the middle of migrating to Java 17, but our development environment has already been migrated, so you may need Java 17 to build locally (even if Zeebe itself still targets Java 11 & 8, depending on the modules).
