### ISSUE TITLE
OutOfMemory in follower

### ISSUE THREAD

**Issue by deepthidevaki** [camunda-cloud/zeebe#7992]
**Describe the bug**

In the release-1.2.0 benchmark, observed that the node which is the follower for all partitions went out of memory. 
Might be related to #7784 

![image](https://user-images.githubusercontent.com/1997478/137317231-2349c090-7811-4d9d-94c5-d9d7d1f959e7.png)

https://console.cloud.google.com/errors/CMz-q-2yh8X-pQE?service=zeebe-broker&time=P7D&project=zeebe-io

**Environment:**
 - Zeebe Version: 1.2.0

**Comment by deepthidevaki** [comment]
Don't know if it is the same reason. I'm trying to get more info from it. VisualVm goes out of memory when I'm analyzing this heap dump :grinning:

**Comment by deepthidevaki** [comment]
Don't know if it is the same reason. I'm trying to get more info from it. VisualVm goes out of memory when I'm analyzing this heap dump :grinning:

**Comment by deepthidevaki** [comment]
Thanks @oleschoenburg Are you able to compute GC root? That gets stuck for me. It makes progress for a while and then everything hangs. Increasing memory did not help.

**Comment by npepinpe** [comment]
Do we think this might now be fixed?

**Comment by deepthidevaki** [comment]
Not sure. There might have been multiple reasons for it. #8044 might be one, which is already fixed. But the state was also similar to #7694 for which the root cause is not clear, but may be fixed by #8038.

**Comment by romansmirnov** [comment]
Re https://github.com/camunda-cloud/zeebe/issues/7992#issuecomment-947402210:

> No idea. We don't see any errors in the logs. It is possible that if there was an error, the future is not completed (because of improper error handling) and the streamProcessor waiting on that future waits for ever. But we don't see any error in the logs. Another hypothesis is the it is stuck in a loop or so, so the task never completes. One idea was that the reader is stuck trying to read the last position from the journal. Howerver no evidence in logs or heapdump to confirm this. What is interesting is there are two partitions of which the StreamProcessor is in this state.

To my understanding, the two Actor Threads `Broker-2-zb-actors-0` and `Broker-2-zb-actors-2` are not scheduled anymore. Thus, they do not execute any Actor Task (and Actor Jobs).

When checking the heap dump, the Actor Threads do not have the `Thread` label assigned:
![image](https://user-images.githubusercontent.com/2368139/145853897-211a8aac-f226-45b0-af6a-37b56e7dcbe6.png)

Additionally, the thread group (which manages all scheduled threads) does not contain both Actor Threads:
![image](https://user-images.githubusercontent.com/2368139/145854444-85ba1e6e-2c19-4220-9b6a-7edae5c48966.png)

There is also other information indicating that the threads are not scheduled (i.e., terminated) anymore.

When checking the Actor's source code, then the actor handles only all unhandled exceptions of type `Exception`, like 

https://github.com/camunda-cloud/zeebe/blob/2dee25fcb748d8a9c6457eee465d08fd5a4d5471/util/src/main/java/io/camunda/zeebe/util/sched/ActorJob.java#L36-L58

As mentioned by @deepthidevaki, when opening the appender an exception occurred that has not been handled correctly. But with the given facts above, I assume that an exception of type `Throwable` (but not `Exception`) has been thrown, which wasn't handled by the `LogStream` but also not by the `Actor`. As a consequence of the unhandled throwable exception, the actor threads terminated. The impact is that other Actors and Raft Threads assume that the Log Stream Actor is active, and thus, they additional work (i.e., Actor Jobs) to the Log Stream Actor. The Actor Jobs piles up which leads to an increasing java heap size that results at some point in an `OutOfMemoryError`.

To my understanding, the fix provided with #8038 does not solve the issue sufficiently. Meaning, it still might happen that a throwable exception is thrown and not handled which terminates the corresponding actor thread.

#7807 already describes the issue of terminated actor threads, which was observed in case of an `OutOfMemoryError` in the direct memory. The fix implements a handler to handle uncaught exceptions and in the case of `VirtualMachineError` the application is exited. However, in case there is any other `Throwalbe` (but not `Exception`) thrown then this issue might still occur as they are not handled improperly.

A possible solution would be to catch `Throwable` in the actor job, and if it is not a `VirtualMachineError` then let the actor handle that situation. In the case of the Log Stream, it could close itself and complete exceptionally the appender future so that the Stream Process can handle that situation. Otherwise, the error is logged. But the actor threads remains running and does not get terminated.

**Comment by romansmirnov** [comment]
Depends on #8327
