### ISSUE TITLE
Configure elasticseach index shards and replication

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#8004]
**Is your feature request related to a problem? Please describe.**

If I want to use an replicated and sharded elasticsearch setup for the exporter I need to be able to configure the replication and shards for the exporter indices. 

**Describe the solution you'd like**

Have a elasticsearch exporter configuration available which allows me to set the replication and shards. I think for the first iteration it is okay to have a global configuration which applies for all indices and it is not needed to configure it per indices.

**Describe alternatives you've considered**

Without the settings option I have to manually re-configure/override the indices templates of the Zeebe exporter.

**Comment by npepinpe** [comment]
I need a bit more info here. What happens when this is not configured? Is this something required for CCSaaS?

**Comment by romansmirnov** [comment]
@npepinpe,

When looking through the elastic templates, I noticed in two cases the sharding is set to 3:
* [`zeebe-record-job-template.json`](https://github.com/camunda-cloud/zeebe/blob/0e68d34196cad3d3acb2b84de8a9d2d8bbec86f2/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-job-template.json#L10)
* [`zeebe-record-process-instance-template.json`](https://github.com/camunda-cloud/zeebe/blob/0e68d34196cad3d3acb2b84de8a9d2d8bbec86f2/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-process-instance-template.json#L10)

In all other templates, the sharding is set to 1.

Just to my understanding:
* Why does the configuration of the shards differ? Is my assumption correct, because we expect that the process instance and job indexes to be the biggest ones and that's why they are sharded?
* Implementation-wise, whatever is configured by the user, the settings in the templates get overwritten by the user's value? Also, the sharding settings in case of the process instance and job indexes?

**Comment by npepinpe** [comment]
The original commit is https://github.com/camunda-cloud/zeebe/commit/d2eb0bf6d966a44988b59a4178fde6f83acb5614 - I think your assumption is correct, but that's something @sdorokhova or @menski could clarify. I imagine it came from a requirement for Operate.

I would expect that whatever the user sets goes, but we could use these values as default when the user doesn't provide any.

**Comment by menski** [comment]
@romansmirnov the different shard configs came from our observation that these to indices are the ones with the most events, and in a high throughput scenario a single shard can become a bottleneck. Therefore we decided at this point to set them by default to 3, see #3329 for context. Right now I would agree with Nicolas that if the user sets a shard config it should override this.

**Comment by romansmirnov** [comment]
Thanks for the clarification.

A quick follow-up question, do you have an example or idea of how to write a unit/integration test case? :)

**Comment by npepinpe** [comment]
For unit testing, we can just check that the configuration is correctly substituted in the template request. Unfortunately we don't have an example of testing the `ElasticsearchClient` against a mocked backend at the moment, but if you feel up for it you can introduce one. I have a feeling it might be a bit overly complex however, since we use the low level client, but I haven't tried so maybe it's not too bad. But I imagine it will be a no-go for this.

For integration test, you'll see there's already some facilities to assert the created indexes, in `AbstractElasticsearchExporterIntegrationTest#assertIndexSettings()`. Right now the shard number is hard coded, but I'm sure it can be adapted. So you could add a test in `ElasticsearchClientIT` where you configure the shard numbers for the templates, then use an adapted version of the logic found in `assertIndexSettings` to check that the created indexes have the expected shard numbers.

(just a note: the Elasticsearch Exporter tests are pretty terrible right now, in part because we didn't design the exporter correctly for it to be testable, and this is something we're aware of, but as very little work is done in that area it always gets pushed away. that said, if you see obvious things to improve go for it, though I understand this is your first foray there so I wouldn't expect it :slightly_smiling_face:)

**Comment by romansmirnov** [comment]
Thanks, @npepinpe! I will check it out soon.

Another quick question, the implementation differs between [`component templates`](https://github.com/camunda-cloud/zeebe/blob/895c61b98c536ac378597ac5e8215e046ce897a6/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java#L134) and [`value index templates`](https://github.com/camunda-cloud/zeebe/blob/895c61b98c536ac378597ac5e8215e046ce897a6/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporter.java#L137). To my understanding (and in my own words), all `value index templates` inherit the properties from the `component templates`.

However, the `component template` configures the number of shards and replicas. Do you expect to set these values also to whatever the user configured?
