### ISSUE TITLE
Where is source code of the Canunda Cloud Operate?

### ISSUE THREAD

**Issue by Hansin1997** [camunda-cloud/zeebe#8102]
**Description**

I'm looking for source code of the Canunda Cloud Operate, but i couldn't find it.

I need to read the source code cause i wondering how to search process-instance by Elasticsearch with status (COMPLETED,CANCELED,INCIDENT,ACTIVING)

**Comment by npepinpe** [comment]
However, maybe we can get someone from the Operate side to help you out on this one.

**Comment by npepinpe** [comment]
I've talked with the Operate team, and the Elasticsearch schema is not meant to be publicly documented, mostly because it's not part of their public API, i.e. there would be no guarantees of backwards compatibility or anything. Note that they will work in the next year to have a headless query/history API which I hope will solve your issue.

**Comment by Hansin1997** [comment]
Thanks😀
