### ISSUE TITLE
[Medic] Document process for medics to persist logs

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#8331]
**Description**

At the moment we use links to google stackdriver in issues we find in test or production environments, see for example #8017. These logs are available for a limited time. If a issues is not immediately worked on the log might be already deleted and the engineer who is assigned to the issue as no way to investigate the logs anymore. 

Goal of this task is to define a process and document it how logs can be stored to be available for a longer period of time to allow engineers to access them when they are assigned to an issue.

As these logs can have personal information for production environments we should find a way to store them privately or anonymize them before linking in a issue. 

One idea is to save them directly to google drive

![image](https://user-images.githubusercontent.com/516296/145196815-b643d951-d126-4d4e-9bf7-f0cce49510ca.png)

**Comment by multani** [comment]
> As these logs can have personal information for production environments we should find a way to store them privately or anonymize them before linking in a issue.

FYI, we ( @camunda-cloud/sre ) are having a look at how we could enforce stronger separation between dev/int/prod.

It's still under discussion but the current idea would be to have separated Google Cloud projects, one per-environment - this would completely separate the logs.

Also, it's possible to store logs for a longer period of time: logs matching specific filters (to be defined) could be processed differently and stored for `N` days (to be defined) instead of the default value (see [Routing and storage overview](https://cloud.google.com/logging/docs/routing/overview))

It may also be possible to process them and redact some part on the fly, although it may be more involved.

**Comment by oleschoenburg** [comment]
@menski do you have any preferences on *where* I document this? In the end it's not much information, mostly just the screenshot that you have already created. I've thought about adding something to the issue template but since this is not applicable to community contributions that doesn't seem ideal.
