### ISSUE TITLE
Create documentation for API

### ISSUE THREAD

**Issue by KatePopkova** [camunda-cloud/zeebe#8371]
Create documentation that describes how developers can use Zeebe in projects. 

For example, for now it is some kind of problem to  use Zeebe because there are no any description for classes, its fields and methods.  It is not understandable what to use and how for any task in the project that includes Zeebe therefore every time developers have to do some research of Zeebe source codes before using some Zeebe feature in the project that can take much time.

**Comment by npepinpe** [comment]
Hi @KatePopkova! Do you mean documentation in order to contribute to Zeebe, or to use Zeebe in your own application? If it's the latter, is https://docs.camunda.io not sufficient? You have [guides](https://docs.camunda.io/docs/guides/) section, a [high level overview of Zeebe](https://docs.camunda.io/docs/components/zeebe/zeebe-overview/), a [clients](https://docs.camunda.io/docs/apis-clients/java-client/index/) section, a [reference](https://docs.camunda.io/docs/reference/) section, and the [self managed](https://docs.camunda.io/docs/self-managed/zeebe-deployment/index/) section which offer different levels of documentation for users. If that's not sufficient, issues about documentation should be opened in [the Camunda Cloud documentation project](https://github.com/camunda-cloud/camunda-cloud-documentation/).

**Comment by KatePopkova** [comment]
Hello @npepinpe.
Thank you very much for your help. I have created the issue in a proper place: https://github.com/camunda-cloud/camunda-cloud-documentation/issues/503

**Comment by npepinpe** [comment]
Then I'll close this for now.
