### ISSUE TITLE
Zbctl error when connecting to a secure cluster

### ISSUE THREAD

**Issue by mihneastaub** [camunda-cloud/zeebe#8739]
Hello Guys,

I have a secure zeebe cluster, that was deployed with the helm-chart in a kubernetes environment. I wanted to connect to the cluster using the command zbctl status, but this error appears:
`Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"`

I have tried to use the command also to point to the certificate, but the same issue appear (`zbctl status --certPath <path to the cert>`):
`Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"`

**To Reproduce**
Deploy a 3 replicas zeebe-cluster with TLS enable in a kubernetes environment. I have used this [helm-chart](https://github.com/camunda-community-hub/camunda-cloud-helm/tree/zeebe-zeeqs-helm-1.1.5/charts/zeebe-cluster-helm).

After the cluster is working and everything is up and running, run the command `zbctl status --certPath <path of the cert>` and the error will appear.

**Expected behavior**

When the cluster is deployed and everything works as expected, the command should run very smooth and also the command zbctl status --insecure should not work at all.

I want to mention, that I do not use any other command, only status.

**Comment by npepinpe** [comment]
The gateway has two type of security configuration, since it exposes two different ports/API: the port via which it communicates with the client, and the port via which it communicates with the rest of the cluster.

Right now, if you want both to use TLS, then you need to configure both. That also gives you the advantage of being able to configure either one, and also use different certificates (one for external communication, one for internal communication).

So on the gateway, you need to follow both docs:

- [Securing client/gateway communication](https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/secure-client-communication/)
- [Securing inter-cluster communication](https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/secure-cluster-communication/)

From your error, I'm going to guess you configured only the inter cluster communication, which means your gateway is talking to clients in plaintext, but your client is trying to use TLS, and thus you get the error above.

**Comment by mihneastaub** [comment]
@npepinpe 

Thank you very much for all the information and guide here. I did not know that for this client secure communication need to create another certificate.

I have create the new certificate and test this and now is working as expected.
